### ISSUE TITLE
add rtutracker.org

### ISSUE THREAD

**Issue by bodywithoutorgans** [mabakay/torrenter#2]
Please add rutracker search to the list. It has many films not available anywhere else.
https://rutracker.org/forum/tracker.php?nm={0}

**Comment by mabakay** [comment]
I can see it is a private tracker. It is not a first request for private trackers but they have such a disadvantage that they are specific. In the end we would easily end up with dozens of them (every for every user). But I have some idea. I think "script settings page" is what you are asking for.

**Comment by mabakay** [comment]
You can now configure your own engines :-)
