### ISSUE TITLE
Add rottentomatoes

### ISSUE THREAD

**Issue by kyra-b** [mabakay/torrenter#4]
please add support for rottentomatoes. I'm assuming that just adding rottentomatoes to the match: wouldnt work? if so i could do a pull request

**Comment by mabakay** [comment]
> I'm assuming that just adding rottentomatoes to the match: wouldnt work?

Not exactly, but hey its fine idea. Try to do a pull request and if you can't make it, I'll try to add www.rottentomatoes.com in my spare time.
